-- =========================================================
-- Community 신고 처리 (경량형)
-- 신고 접수 -> 운영진 검토 -> 조치 기록의 3단계만 관리합니다.
-- 실시간 모니터링, 누적 제재 점수, 신고 간 부모-자식 관계는 두지 않습니다.
-- =========================================================

create table if not exists public.community_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id bigint not null,
  reason text not null check (char_length(btrim(reason)) between 2 and 300),
  status text not null default 'pending'
    check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  moderation_action text not null default 'none'
    check (moderation_action in ('none', 'warning', 'content_deleted')),
  reviewer_id uuid references auth.users(id) on delete set null,
  review_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_reports_one_report_per_target
    unique (reporter_id, target_type, target_id)
);

create index if not exists community_reports_status_created_idx
  on public.community_reports (status, created_at desc);

create index if not exists community_reports_target_idx
  on public.community_reports (target_type, target_id);

-- 다형 대상(post/comment)에 FK를 억지로 두지 않고 insert 시 존재 여부와 자기 신고를 검증합니다.
create or replace function public.validate_community_report_target()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_author uuid;
begin
  if new.target_type = 'post' then
    select author_id into target_author
    from public.posts
    where id = new.target_id;
  elsif new.target_type = 'comment' then
    select author_id into target_author
    from public.comments
    where id = new.target_id
      and deleted_at is null;
  end if;

  if target_author is null then
    raise exception '신고 대상을 찾을 수 없습니다.';
  end if;

  if target_author = new.reporter_id then
    raise exception '본인이 작성한 콘텐츠는 신고할 수 없습니다.';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_community_report_target_trigger
on public.community_reports;

create trigger validate_community_report_target_trigger
before insert on public.community_reports
for each row execute function public.validate_community_report_target();

create or replace function public.is_community_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

alter table public.community_reports enable row level security;

drop policy if exists "community reports insert own" on public.community_reports;
create policy "community reports insert own"
on public.community_reports
for insert
to authenticated
with check (reporter_id = auth.uid());

drop policy if exists "community reports read own or admin" on public.community_reports;
create policy "community reports read own or admin"
on public.community_reports
for select
to authenticated
using (reporter_id = auth.uid() or public.is_community_admin());

drop policy if exists "community reports admin update" on public.community_reports;
create policy "community reports admin update"
on public.community_reports
for update
to authenticated
using (public.is_community_admin())
with check (public.is_community_admin());

-- 검토/조치 기록용 경량 RPC.
-- 실제 콘텐츠 삭제는 기존 게시글/댓글 삭제 흐름을 사용하고,
-- 이 함수는 검토 결과와 조치 이력만 기록합니다.
create or replace function public.review_community_report(
  p_report_id bigint,
  p_status text,
  p_action text default 'none',
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_community_admin() then
    raise exception '관리자만 신고를 검토할 수 있습니다.';
  end if;

  if p_status not in ('reviewing', 'resolved', 'dismissed') then
    raise exception '올바르지 않은 신고 상태입니다.';
  end if;

  if p_action not in ('none', 'warning', 'content_deleted') then
    raise exception '올바르지 않은 조치 값입니다.';
  end if;

  update public.community_reports
  set
    status = p_status,
    moderation_action = p_action,
    reviewer_id = auth.uid(),
    review_note = nullif(btrim(p_note), ''),
    reviewed_at = case when p_status in ('resolved', 'dismissed') then now() else reviewed_at end,
    updated_at = now()
  where id = p_report_id;

  if not found then
    raise exception '신고 내역을 찾을 수 없습니다.';
  end if;
end;
$$;

grant execute on function public.review_community_report(bigint, text, text, text)
to authenticated;

notify pgrst, 'reload schema';
