-- Community 신고 처리 (경량형)
-- 신고 접수 -> 운영진 검토 -> 조치 기록의 3단계만 관리합니다.
-- 실시간 모니터링, 누적 제재 점수, 신고 간 부모-자식 관계는 두지 않습니다.

create table if not exists public.community_reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references auth.users(id) on delete cascade,
  target_type text not null check (target_type in ('post', 'comment')),
  target_id bigint not null,
  reason text not null check (char_length(btrim(reason)) between 2 and 300),
  status text not null default 'pending'
    check (status in ('pending', 'reviewing', 'resolved', 'dismissed')),
  moderation_action text not null default 'none'
    check (moderation_action in ('none', 'warning', 'content_deleted')),
  reviewer_id uuid references auth.users(id) on delete set null,
  review_note text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_reports_one_report_per_target
    unique (reporter_id, target_type, target_id)
);

create index if not exists community_reports_status_created_idx
  on public.community_reports (status, created_at desc);

create index if not exists community_reports_target_idx
  on public.community_reports (target_type, target_id);

-- 다형 대상(post/comment)에 FK를 억지로 두지 않고 insert 시 존재 여부와 자기 신고를 검증합니다.
create or replace function public.validate_community_report_target()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  target_author uuid;
begin
  if new.target_type = 'post' then
    select author_id into target_author
    from public.posts
    where id = new.target_id;
  elsif new.target_type = 'comment' then
    select author_id into target_author
    from public.comments
    where id = new.target_id
      and deleted_at is null;
  end if;

  if target_author is null then
    raise exception '신고 대상을 찾을 수 없습니다.';
  end if;

  if target_author = new.reporter_id then
    raise exception '본인이 작성한 콘텐츠는 신고할 수 없습니다.';
  end if;

  return new;
end;
$$;

drop trigger if exists validate_community_report_target_trigger
on public.community_reports;

create trigger validate_community_report_target_trigger
before insert on public.community_reports
for each row execute function public.validate_community_report_target();

create or replace function public.is_community_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

alter table public.community_reports enable row level security;

drop policy if exists "community reports insert own" on public.community_reports;
create policy "community reports insert own"
on public.community_reports
for insert
to authenticated
with check (reporter_id = auth.uid());

drop policy if exists "community reports read own or admin" on public.community_reports;
create policy "community reports read own or admin"
on public.community_reports
for select
to authenticated
using (reporter_id = auth.uid() or public.is_community_admin());

drop policy if exists "community reports admin update" on public.community_reports;
create policy "community reports admin update"
on public.community_reports
for update
to authenticated
using (public.is_community_admin())
with check (public.is_community_admin());

-- 검토/조치 기록용 경량 RPC.
-- 일반 검토는 상태와 경고 이력만 기록합니다.
-- 실제 콘텐츠 삭제는 아래 delete_reported_community_content RPC에서만 수행합니다.
create or replace function public.review_community_report(
  p_report_id bigint,
  p_status text,
  p_action text default 'none',
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_community_admin() then
    raise exception '관리자만 신고를 검토할 수 있습니다.';
  end if;

  if p_status not in ('reviewing', 'resolved', 'dismissed') then
    raise exception '올바르지 않은 신고 상태입니다.';
  end if;

  if p_action not in ('none', 'warning', 'content_deleted') then
    raise exception '올바르지 않은 조치 값입니다.';
  end if;

  update public.community_reports
  set
    status = p_status,
    moderation_action = p_action,
    reviewer_id = auth.uid(),
    review_note = nullif(btrim(p_note), ''),
    reviewed_at = case when p_status in ('resolved', 'dismissed') then now() else reviewed_at end,
    updated_at = now()
  where id = p_report_id;

  if not found then
    raise exception '신고 내역을 찾을 수 없습니다.';
  end if;
end;
$$;

grant execute on function public.review_community_report(bigint, text, text, text)
to authenticated;

-- - 운영진 신고 대상 실제 삭제
-- - 게시글: 댓글/좋아요/태그 연결/조회 기록과 게시글을 함께 삭제
-- - 댓글: 선택 댓글과 모든 하위 답글을 함께 삭제
-- - 삭제 후 같은 대상을 가리키는 신고는 모두 처리 완료/content_deleted로 기록

create or replace function public.delete_reported_community_content(
  p_report_id bigint,
  p_note text default null
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  report_row public.community_reports%rowtype;
  deleted_kind text;
begin
  if not public.is_community_admin() then
    raise exception '관리자만 신고된 콘텐츠를 삭제할 수 있습니다.';
  end if;

  select *
  into report_row
  from public.community_reports
  where id = p_report_id;

  if not found then
    raise exception '신고 내역을 찾을 수 없습니다.';
  end if;

  if report_row.target_type = 'post' then
    if exists (
      select 1 from public.posts p where p.id = report_row.target_id
    ) then
      -- 게시글 자식 데이터를 먼저 제거합니다.
      -- comments 삭제 시 comment_likes는 FK cascade로 함께 정리됩니다.
      delete from public.comments
      where post_id = report_row.target_id;

      delete from public.post_likes
      where post_id = report_row.target_id;

      delete from public.post_tags
      where post_id = report_row.target_id;

      delete from public.post_views
      where post_id = report_row.target_id;

      delete from public.posts
      where id = report_row.target_id;
    end if;

    deleted_kind := 'post';

  elsif report_row.target_type = 'comment' then
    -- 부모 댓글 신고라면 그 아래 답글까지 같은 SQL 문장에서 함께 삭제합니다.
    with recursive comment_tree as (
      select c.id
      from public.comments c
      where c.id = report_row.target_id

      union all

      select child.id
      from public.comments child
      join comment_tree parent on child.parent_id = parent.id
    )
    delete from public.comments c
    using comment_tree t
    where c.id = t.id;

    deleted_kind := 'comment';

  else
    raise exception '지원하지 않는 신고 대상입니다.';
  end if;

  -- 같은 콘텐츠를 여러 명이 신고했더라도 운영진이 삭제하면 모두 같은 결과로 종결합니다.
  update public.community_reports
  set
    status = 'resolved',
    moderation_action = 'content_deleted',
    reviewer_id = auth.uid(),
    review_note = coalesce(
      nullif(btrim(p_note), ''),
      review_note,
      '운영진 검토 후 신고 대상 콘텐츠 삭제'
    ),
    reviewed_at = now(),
    updated_at = now()
  where target_type = report_row.target_type
    and target_id = report_row.target_id;

  return deleted_kind;
end;
$$;

revoke all on function public.delete_reported_community_content(bigint, text)
from public;

grant execute on function public.delete_reported_community_content(bigint, text)
to authenticated;

notify pgrst, 'reload schema';
