// 로딩/에러 화면 공용 sx 스타일
export const styles = {
  page: {
    bgcolor: "background.default",
    flex: 1,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    py: 10,
    px: 2,
  },
  container: { maxWidth: 900, mx: "auto", textAlign: "center" },
  badge: {
    display: "inline-block",
    bgcolor: "primary.main",
    color: "#fff",
    fontWeight: 700,
    fontSize: "0.9rem",
    borderRadius: 5,
    px: 2.5,
    py: 1,
    mb: 3,
  },
  bodyText: { lineHeight: "26px" },
  progressWrap: { maxWidth: 650, mx: "auto", mb: 6 },
  progressBar: { height: 10, borderRadius: 5 },
  progressRow: { display: "flex", justifyContent: "space-between", mt: 1.5 },
  cardRow: { display: "flex", justifyContent: "center", gap: 3, flexWrap: "wrap" },
  icon18: { width: 18, height: 18 },
  icon20: { width: 20, height: 20 },
  icon44: { width: 44, height: 44 },
  errorIconWrap: {
    width: 110,
    height: 110,
    mx: "auto",
    mb: 4,
    borderRadius: "50%",
    border: "1px dashed",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  actionBtn: { height: 48, fontSize: "0.95rem" },
  helpLink: { fontWeight: 600, fontSize: "0.9rem" },
  card: {
    flex: "1 1 300px",
    maxWidth: 360,
    p: 3,
    borderRadius: 3,
    textAlign: "left",
    border: "1px solid",
  },
  avatar: { width: 40, height: 40, mb: 1.5 },
};
